org: sixfive
app: medic52
service: slackops # NOTE: update this with your service name

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'medic52'}
  region: ${opt:region, 'us-west-2'}

  # you can define service wide environment variables here
  environment:
    # KMS_ENCRYPTED_HOOK_URL: you can use ENCRYPTED_HOOK_URL if you want
    # Uses AWS SSM to store the URL, see README for details on how to do this
    UNENCRYPTED_HOOK_URL: ${self:custom.slackwebhook.${opt:region, self:provider.region}}

  # Give this lambda the ability to deal with CodePipline manual approvals
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
           - "codepipeline:PutApprovalResult"
          Resource: { "Fn::Join" : [":", ["arn:aws:codepipeline",{ "Ref" : "AWS::Region" },{ "Ref" : "AWS::AccountId" },"*/*/ManualApproval" ] ]  }


plugins:
  - serverless-offline-sns

custom:
  prefix:
    local: -${opt:stage, self:provider.stage}
    dev: -${opt:stage, self:provider.stage}
    staging: -${opt:stage, self:provider.stage}
    master: ''
  slackwebhook:
    #############################################
    # Add each region you operate in 
    # Add the Slack Webhook URL here for each
    ############################################
    us-west-2: "https://hooks.slack.com/services/xxxxxxxxxx/xxxxxxxxxx/xxxxxxxxxx"
    ap-southeast-2: "https://hooks.slack.com/services/xxxxxxxxxx/xxxxxxxxxx/xxxxxxxxxx"
  serverless-offline-sns:
    port: 4002 # a free port for the sns server to run on
    debug: false
    # host: 0.0.0.0 # Optional, defaults to 127.0.0.1 if not provided to serverless-offline
    # sns-endpoint: http://127.0.0.1:4567 # Optional. Only if you want to use a custom endpoint
    # accountId: 123456789012 # Optional
  apiEndpoint:
    Fn::Join:
    - ""
    - - "https://"
      - Ref: "ApiGatewayRestApi"
      - ".execute-api."
      - ${self:provider.region}.
      - Ref: "AWS::URLSuffix"
      - "/"
      - ${self:provider.stage}
      - "/webhook"
  topicName: ${self:service}-aggregate-${opt:stage, self:provider.stage}    # Can be refered using ${self:custom.topicName}
  topicArn:
      Fn::Join:
        - ":"
        - - "arn:aws:sns"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - ${self:custom.topicName}

functions:
  aggregator:
    handler: handler.aggregator
    events:
      - sns:
          arn: ${self:custom.topicArn}
          topicName: ${self:custom.topicName}
  slackincoming:
    handler: handler.incomingwebhook
    events: 
      - http:
          method: post
          path: webhook


# Give 
resources:
  Resources:
    ssmSlackAppURL:
      Type: "AWS::SSM::Parameter"
      Properties: 
        Name: SLACK_APP_HOOK_URL${self:custom.prefix.${opt:stage, self:provider.stage}}
        Type: String
        Value: ${self:custom.slackwebhook.${opt:region, self:provider.region}}
  
    ssmSnsTopic:
      Type: "AWS::SSM::Parameter"
      Properties: 
        Name: /SlackSnSTopic${self:custom.prefix.${opt:stage, self:provider.stage}}
        Type: String
        Value:
          Ref: SnsTopic

    SnsTopic:
        Type: AWS::SNS::Topic
        Properties:
          DisplayName: "SNS Slack Topic"
          TopicName: ${self:custom.topicName}

    SnsTopicPolicy:
        Type: AWS::SNS::TopicPolicy
        DependsOn:
          - SnsTopic
        Properties:
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowCloudWatchToPublish
                Effect: Allow
                Principal:
                  AWS: '*'
                Action: 'sns:Publish'
                Resource:
                  Ref: SnsTopic
          Topics:
            - Ref: SnsTopic

  Outputs: 
    SlackWebhookURL:
        Description: The AWS endpoint to put in https://api.slack.com/apps > Interactive Components > Interactivity & Shortcuts > Interactivity > Request URL
        Value:
          ${self:custom.apiEndpoint}
    SlackWebhookApp:
        Description: When you update the endpoint, ensure its in the same app that has this Webhook endpoint in https://api.slack.com/apps 
        Value: ${self:custom.slackwebhook.${opt:region, self:provider.region}}
    NotificationARN:
        Description: The endpoint to put in to NotificationARN items and for use in AWS services
        Value:
          Ref: SnsTopic